name: coverage
on:
  workflow_call:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install 🔧
        run: pip3 install -r src/app/requirements.txt --no-cache-dir
      - name: Test 📋
        run: |
          python3 -m coverage run --source=src/app --omit="*_spec.py" -m pytest src
          python3 -m coverage xml -o ./src/resources/coverage/coverage.xml
          genbadge coverage -i ./src/resources/coverage/coverage.xml -o ./src/resources/coverage/coverage.svg
      - name: Commit Results 💾
        uses: stefanzweifel/git-auto-commit-action@v4