name: develop
on:
  push:
    branches: [ develop ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  coverage:
    name: Coverage
    uses: ./.github/workflows/coverage.yaml