name: main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml
  release:
    needs: test
    name: Release
    uses: ./.github/workflows/release.yaml
  merge:
    needs: release
    name: Merge
    uses: ./.github/workflows/merge.yaml